version: "3"

services:
  web:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: flask
    expose:
       - 5000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - web
    ports:
       - "80:80"